"""
ui/main_window.py — Main window and system orchestrator
=========================================================

This module implements the MainWindow: the orchestrator of the PyQt6 goniometry application.
It instantiates all components, connects signals between threads, and controls
the complete lifecycle (launch → session → termination → reporting).

MainWindow Responsibilities:
    1. Instantiate and visually arrange all UI widgets.
    2. Instantiate the workers (CameraWorker, ProcessingWorker) WITHOUT starting them.
    3. Connect signals from workers to widgets in a thread-safe manner.
    4. Manage the state machine (IDLE → READY → RUNNING → STOPPED).
    5. Control the worker lifecycle (start, stop, wait).
    6. Generate the PDF report without freezing the UI (separate thread).
    7. Shut down the application cleanly upon window close.

State Machine:
    IDLE    → Initial state. Camera not started. Form is editable.
    READY   → Patient name filled. Start button enabled.
    RUNNING → Camera and processing active. End button enabled.
    STOPPED → Session ended. PDF, CSV, and History enabled.

Data Flow (thread-safe via pyqtSignal):
    CameraWorker ──frame_ready──► ProcessingWorker (via put_frame, queue)
    ProcessingWorker ──result_ready──► MainWindow._on_result()
    MainWindow._on_result() ──distributes──► VideoWidget, MetricsWidget,
                                             PlotWidget, FingerCardsPanel
"""

import logging
import os
import shutil
from datetime import datetime
from typing import Optional

from PyQt6.QtCore import Qt, QThread, pyqtSignal
from PyQt6.QtWidgets import (
    QFileDialog,
    QGroupBox,
    QHBoxLayout,
    QMainWindow,
    QMessageBox,
    QPushButton,
    QScrollArea,
    QSizePolicy,
    QStatusBar,
    QVBoxLayout,
    QWidget,
)

import config
from session_report import generate_pdf_report
from themes import (
    BUTTON_DANGER_STYLE,
    BUTTON_PRIMARY_STYLE,
    COLOR_ACCENT,
    COLOR_BG_DARK,
    COLOR_BG_MEDIUM,
)

# Import the workers.
from workers.camera_worker import CameraWorker
from workers.processing_worker import ProcessingResult, ProcessingWorker

# Import the UI widgets.
from ui.finger_card_widget import FingerCardsPanel
from ui.log_widget import LogWidget
from ui.metrics_widget import MetricsWidget
from ui.plot_widget import GoniometryPlotWidget
from ui.session_header import SessionHeaderWidget
from ui.video_widget import VideoWidget

# Module-specific logger — facilitates tracking window events.
logger = logging.getLogger(__name__)


# =============================================================================
# AUXILIARY WORKER FOR PDF GENERATION
# =============================================================================

class _PdfGeneratorWorker(QThread):
    """
    Auxiliary thread for generating the PDF report without blocking the UI.

    Why does generate_pdf_report() need a separate thread?
        The generate_pdf_report() function in session_report.py is HEAVY:
        - Reads and parses the entire CSV file (can have thousands of rows).
        - Generates multiple charts with Matplotlib (100–400ms each).
        - Assembles the PDF with FPDF (includes rendering images).
        On slow hardware, this process can take 5–15 seconds.
        If it ran on the main thread, the window would freeze completely
        for that duration — the OS would display "Application Not Responding",
        and the user might force-close it.

        Running in a QThread:
        - The window remains responsive throughout the process.
        - The user can see the progress bar or log updating.
        - The finished_signal notifies MainWindow when the PDF
          is ready, in a thread-safe manner.

    Signals:
        finished_signal(str): Generated PDF path upon successful completion.
        error_signal(str): Error message if generation fails.
    """

    # Carries the generated PDF path upon successful completion.
    finished_signal: pyqtSignal = pyqtSignal(str)

    # Carries the error message if generation fails.
    error_signal: pyqtSignal = pyqtSignal(str)

    def __init__(
        self,
        csv_path: str,
        patient_name: str,
        side: str,
        logo_path: Optional[str] = None,
        parent=None,
    ) -> None:
        """
        Configures the PDF generation parameters.

        Parameters:
            csv_path: Path to the CSV generated by the ended session.
            patient_name: Patient name for the report.
            side: Evaluated hand ("Right" or "Left").
            logo_path: Path to the institutional logo (optional).
            parent: Qt parent widget (optional).
        """
        super().__init__(parent)
        self._csv_path = csv_path
        self._patient_name = patient_name
        self._side = side
        self._logo_path = logo_path

    def run(self) -> None:
        """
        Executes the PDF generation on the separate thread.

        Calls generate_pdf_report() with the configured parameters and
        emits finished_signal with the PDF path or error_signal with
        the error description. Never raises exceptions outside the QThread —
        errors are communicated via signal.
        """
        try:
            pdf_path: str = generate_pdf_report(
                csv_path=self._csv_path,
                patient_name=self._patient_name,
                side=self._side,
                logo_path=self._logo_path,
            )
            # Emits the generated PDF path for MainWindow to display in the dialog.
            self.finished_signal.emit(pdf_path)

        except Exception as exc:
            # Captures any error (empty CSV, Matplotlib failed, disk full etc.)
            # and notifies MainWindow via thread-safe signal.
            logger.error("Failed to generate PDF: %s", exc, exc_info=True)
            self.error_signal.emit(str(exc))


# =============================================================================
# MAIN WINDOW
# =============================================================================

class MainWindow(QMainWindow):
    """
    Main window of the Digital Goniometry application.

    Implements the "Controller" pattern from MVC: concentrates all coordination
    logic in one place, while each widget has a single responsibility.
    MainWindow DOES NOT perform scientific processing — it only connects
    data producers (workers) with data displayers (widgets).

    Current application state:
        self._state: str — one of: "IDLE", "READY", "RUNNING", "STOPPED"
        self._csv_path: str — path to the active session CSV (empty if none)
        self._pdf_worker: Auxiliary QThread for PDF generation (or None)
    """

    def __init__(self, parent=None) -> None:
        """
        Initializes the main window: widgets, workers, signals, and initial state.

        Initialization order:
            1. Window configuration (title, minimum size).
            2. Creation of all UI widgets.
            3. Worker instantiation (WITHOUT starting the threads).
            4. Connection of all signals between workers and widgets.
            5. Visual layout assembly.
            6. Initial state set to "IDLE".

        Why instantiate workers in __init__ but not start them?
            Workers need to exist so their signals can be connected.
            But starting the threads (start()) before the user clicks "Start Session"
            would waste CPU and camera resources even when the app is idle.

        Parameters:
            parent: Qt parent widget (optional). Usually None for main window.
        """
        super().__init__(parent)

        # --- Window title and size ---
        self.setWindowTitle(config.APP_TITLE)
        self.setMinimumSize(config.WINDOW_MIN_WIDTH, config.WINDOW_MIN_HEIGHT)
        self.setStyleSheet(f"QMainWindow {{ background-color: {COLOR_BG_DARK}; }}")

        # --- Internal state ---
        # String controlling which buttons are enabled and method behavior.
        # Centralizing in one variable avoids scattered logic.
        self._state: str = "IDLE"

        # Path to the active session CSV. Set in _start_session().
        # Used by _gerar_relatorio() and _exportar_csv().
        self._csv_path: str = ""

        # PDF generation worker — we keep a reference to prevent garbage collection
        # before the PDF finishes generating.
        self._pdf_worker: Optional[_PdfGeneratorWorker] = None

        # === COMPONENT CREATION ===
        self._create_widgets()

        # === WORKER INSTANTIATION ===
        self._create_workers()

        # === SIGNAL CONNECTION ===
        self._connect_signals()

        # === LAYOUT ASSEMBLY ===
        self._build_layout()

        # === STATUS BAR ===
        self._status_bar = QStatusBar()
        self.setStatusBar(self._status_bar)
        self._status_bar.showMessage("Ready. Fill in patient data to start.")

        # === INITIAL STATE ===
        # Starts in IDLE: no buttons enabled except the form.
        self._set_state("IDLE")

        logger.info("MainWindow successfully initialized.")

    # =========================================================================
    # COMPONENT CREATION
    # =========================================================================

    def _create_widgets(self) -> None:
        """
        Instantiates all UI widgets.

        Kept separate from __init__ for better organization and easier
        individual unit testing of widgets.
        """
        # Header with patient form and timer.
        self.session_header = SessionHeaderWidget()

        # Video frame display with goniometric overlay.
        self.video_widget = VideoWidget()

        # Side panel with system metric cards.
        self.metrics_widget = MetricsWidget()

        # Live TAM chart for all 5 fingers.
        self.plot_widget = GoniometryPlotWidget()

        # Panel with 5 individual clinical cards per finger.
        self.finger_cards = FingerCardsPanel()

        # System event log with timestamps.
        self.log_widget = LogWidget()

        # --- Session control buttons ---

        # New Session Button — to reset the system at any time
        self.btn_new_session = QPushButton("🔄  New Session")
        self.btn_new_session.setToolTip("Clears all on-screen data to allow registering a new patient or clean test.")

        # Main Start Button — highlighted green style.
        self.btn_start = QPushButton("▶  Start Session")
        self.btn_start.setStyleSheet(BUTTON_PRIMARY_STYLE)
        self.btn_start.setToolTip("Starts video capture and goniometric processing.")

        # End Session Button — red style for destructive/final action.
        self.btn_end = QPushButton("■  End Session")
        self.btn_end.setStyleSheet(BUTTON_DANGER_STYLE)
        self.btn_end.setToolTip("Ends capture and finalizes the CSV file.")

        # Post-processing buttons — default theme styles.
        self.btn_pdf = QPushButton("📄  Generate PDF Report")
        self.btn_pdf.setToolTip("Generates the clinical PDF report from the ended session CSV.")

        self.btn_csv = QPushButton("💾  Export CSV")
        self.btn_csv.setToolTip("Copies the session CSV file to a chosen location.")

        self.btn_historico = QPushButton("📁  Open Sessions Folder")
        self.btn_historico.setToolTip("Opens the folder where session files are saved.")

    def _create_workers(self) -> None:
        """
        Instantiates the camera and processing workers WITHOUT starting the threads.

        Workers are created here so their signals can be connected in
        _connect_signals(). The threads only start when the user clicks
        "Start Session" — not before.
        """
        self.camera_worker = CameraWorker(parent=self)
        self.processing_worker = ProcessingWorker(parent=self)
        # Initialize the worker with the current UI value
        self.processing_worker.set_evaluated_hand(self.session_header.get_session_info()["hand"])

    def _connect_signals(self) -> None:
        """
        Connects all signals between workers, widgets, and MainWindow methods.

        Why centralize here?
            Keeping all connections in a single method creates a readable
            "routing table" for the system. When debugging component communication,
            you just look here to see who talks to whom.

        Established connections:
            camera_worker.frame_ready   → processing_worker.put_frame()
            camera_worker.fps_updated   → video_widget.set_fps()
            camera_worker.camera_error  → _on_camera_error()
            processing_worker.result_ready   → _on_result()
            processing_worker.processing_error → log_widget.log()
            session_header textChanged  → _on_patient_name_changed()
            btn_* .clicked              → action slots
        """
        # --- Camera Worker → Processing Worker ---
        # AutoConnection (default): Qt detects they are in different threads
        # and uses a queued connection (thread-safe).
        # We DO NOT use DirectConnection here because it would execute directly on
        # the CameraWorker thread, and put_frame() accesses the Queue — a safe
        # operation, but DirectConnection is unnecessary when AutoConnection works.
        self.camera_worker.frame_ready.connect(self.processing_worker.put_frame)

        # --- Camera Worker → VideoWidget (FPS) ---
        self.camera_worker.fps_updated.connect(self.video_widget.set_fps)

        # --- Camera Worker → Error handling ---
        self.camera_worker.camera_error.connect(self._on_camera_error)

        # --- Processing Worker → MainWindow (main result) ---
        self.processing_worker.result_ready.connect(self._on_result)

        # --- Processing Worker → LogWidget (non-fatal errors) ---
        self.processing_worker.processing_error.connect(self.log_widget.log_error)
        
        # --- UI Header → Processing Worker (Hand changes) ---
        self.session_header.hand_changed.connect(self.processing_worker.set_evaluated_hand)

        # --- Processing Worker → PlotWidget (clear charts on hand change) ---
        self.processing_worker.hand_side_reset.connect(self.plot_widget.clear_data)

        # --- Form → readiness check ---
        # Each time the name field text changes, we check if the Start button
        # should be enabled. textChanged fires for each character.
        self.session_header._input_patient.textChanged.connect(
            self._on_patient_name_changed
        )

        # --- Buttons → actions ---
        self.btn_new_session.clicked.connect(self._new_session)
        self.btn_start.clicked.connect(self._start_session)
        self.btn_end.clicked.connect(self._end_session)
        self.btn_pdf.clicked.connect(self._gerar_relatorio)
        self.btn_csv.clicked.connect(self._exportar_csv)
        self.btn_historico.clicked.connect(self._abrir_historico)

    # =========================================================================
    # LAYOUT ASSEMBLY
    # =========================================================================

    def _build_layout(self) -> None:
        """
        Assembles the widget and layout hierarchy in the main window.

        Final layout (Central QVBoxLayout):
            1. SessionHeaderWidget          — top, fixed height
            2. QHBoxLayout:
               VideoWidget (stretch=3) │ MetricsWidget (stretch=2)
            3. GoniometryPlotWidget         — fixed height 220px
            4. FingerCardsPanel             — fixed height
            5. LogWidget                    — max height 120px
            6. Button row QHBoxLayout       — fixed height

        Why use stretch factors in the video QHBoxLayout?
            stretch=3 for video and stretch=2 for metrics results in a
            60%/40% ratio, which on most monitors translates to ~768px/512px.
            This keeps the video large enough to view the overlay without
            reducing metrics to an illegible size.
        """
        # =========================================================
        # 1. Central ScrollArea Configuration
        # =========================================================
        scroll_area = QScrollArea()
        scroll_area.setWidgetResizable(True)
        scroll_area.setStyleSheet(f"QScrollArea {{ border: none; background: {COLOR_BG_DARK}; }}")
        self.setCentralWidget(scroll_area)

        # Container widget inside the ScrollArea.
        container_widget = QWidget()
        scroll_area.setWidget(container_widget)

        # Main vertical layout.
        main_layout = QVBoxLayout(container_widget)
        main_layout.setContentsMargins(8, 8, 8, 8)
        main_layout.setSpacing(6)

        # Increase the minimum height for the video and metrics
        # to ensure good viewing. The scroll will handle the rest.
        self.video_widget.setMinimumHeight(450)
        self.metrics_widget.setMinimumHeight(450)

        # --- 1. Session header ---
        main_layout.addWidget(self.session_header)

        # --- 2. Middle row: Video + Metrics ---
        mid_row = QHBoxLayout()
        mid_row.setSpacing(6)

        # Video: occupies ~60% of middle row width.
        mid_row.addWidget(self.video_widget, stretch=3)

        # Metrics: occupies ~40% of middle row width.
        mid_row.addWidget(self.metrics_widget, stretch=2)

        main_layout.addLayout(mid_row)

        # --- 3. Live TAM Chart ---
        # Increase chart height for better readability
        self.plot_widget.setMinimumHeight(280)
        main_layout.addWidget(self.plot_widget)

        # --- 4. Individual finger cards ---
        # Maintain internal scroll for cards (if screen is very narrow)
        # or just set fixed height for them.
        cards_scroll = QScrollArea()
        cards_scroll.setWidget(self.finger_cards)
        cards_scroll.setWidgetResizable(True)
        cards_scroll.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        cards_scroll.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        cards_scroll.setStyleSheet(
            f"QScrollArea {{ border: none; background: {COLOR_BG_DARK}; }}"
        )
        cards_scroll.setFixedHeight(310)

        main_layout.addWidget(cards_scroll)

        # --- 5. Event log ---
        self.log_widget.setMinimumHeight(150)
        main_layout.addWidget(self.log_widget)

        # --- 6. Button bar ---
        main_layout.addLayout(self._build_button_row())

    def _build_button_row(self) -> QHBoxLayout:
        """
        Builds the horizontal row with all control buttons.

        Button order:
            [Start] [End] | [Generate PDF] [Export CSV] [Open Folder]

        The visual separator (stretch) between the two groups distinguishes
        session actions (left) from export actions (right).

        Returns:
            QHBoxLayout ready to be added to the main layout.
        """
        btn_row = QHBoxLayout()
        btn_row.setSpacing(8)

        # Left group: session control.
        btn_row.addWidget(self.btn_new_session)
        btn_row.addWidget(self.btn_start)
        btn_row.addWidget(self.btn_end)

        # Elastic separator between button groups.
        btn_row.addStretch()

        # Right group: export and navigation.
        btn_row.addWidget(self.btn_pdf)
        btn_row.addWidget(self.btn_csv)
        btn_row.addWidget(self.btn_historico)

        return btn_row

    # =========================================================================
    # STATE MACHINE
    # =========================================================================

    def _set_state(self, state: str) -> None:
        """
        Centralizes enabling and disabling buttons based on the state.

        Why centralize in _set_state() instead of enabling/disabling
        buttons directly in each action method?

            Without centralization, each method (start, end, etc.) would need
            to know and manipulate ALL buttons. If a new button is added
            in the future, ALL methods would need updating. With _set_state(),
            we just add the new button here and it is correctly managed
            in all states without changing anything else.

            This is the "State Machine" pattern applied to UI: state is the source of truth,
            and buttons react to state — not vice-versa.

        Valid transitions:
            IDLE    → READY  (when name is filled)
            READY   → RUNNING (on clicking Start)
            RUNNING → STOPPED (on clicking End)
            STOPPED → READY  (on filling name for new session)

        Parameters:
            state: String identifying the new state.
                   Valid values: "IDLE", "READY", "RUNNING", "STOPPED".
        """
        self._state = state

        # --- Session control buttons ---
        # New Session: available only after ending a session.
        self.btn_new_session.setEnabled(state == "STOPPED")

        # Start: enabled only when there is data to start (READY).
        self.btn_start.setEnabled(state == "READY")

        # End: enabled only during active recording (RUNNING).
        self.btn_end.setEnabled(state == "RUNNING")

        # --- Export buttons ---
        # Enabled only after formal session termination (STOPPED).
        # In RUNNING, the CSV is still being written — exporting would be inconsistent.
        self.btn_pdf.setEnabled(state == "STOPPED")
        self.btn_csv.setEnabled(state == "STOPPED")
        self.btn_historico.setEnabled(state in ("IDLE", "READY", "STOPPED"))

        # --- Form fields ---
        # Locked during RUNNING to avoid accidental alteration of
        # identifying data while the session is recording.
        self.session_header.set_fields_enabled(state != "RUNNING")

        # --- Status bar message ---
        status_messages = {
            "IDLE":    "Fill in patient data to enable session start.",
            "READY":   "Ready to start. Click 'Start Session'.",
            "RUNNING": "Session in progress — capturing and processing data...",
            "STOPPED": "Session ended. You can generate the PDF report or export the CSV.",
        }
        self._status_bar.showMessage(status_messages.get(state, ""))

        logger.debug("State changed to: %s", state)

    # =========================================================================
    # RESULT AND ERROR SLOTS
    # =========================================================================

    def _on_result(self, result: object) -> None:
        """
        Receives and distributes ProcessingResult to all widgets.

        Called ~30 times/second by the result_ready signal from ProcessingWorker.
        Must be fast: only distributes data, no calculations.

        This method runs on the main thread (Qt thread), guaranteed by
        Qt's signal system. We never access widgets from inside a
        QThread — always via this connected slot.

        Parameters:
            result: ProcessingResult object emitted by ProcessingWorker.
                    Typed as 'object' because pyqtSignal(ProcessingResult)
                    is not directly supported — we cast here.
        """
        # Cast to the correct type — safe because only ProcessingWorker
        # emits result_ready, always with ProcessingResult.
        r: ProcessingResult = result  # type: ignore[assignment]

        # Updates the video frame with goniometric overlay.
        self.video_widget.update_frame(r.frame_overlay)

        # Updates FPS, Frame#, and hand state cards.
        self.metrics_widget.update_from_result(r)

        # Updates the live TAM chart for 5 fingers.
        self.plot_widget.update_data(r.angles_smooth, r.hand_detected)

        # Updates the 5 individual cards with clinical metrics and mini-charts.
        # get_tam_buffers() returns a thread-safe copy of the worker's deques.
        self.finger_cards.update_all(
            finger_states=r.hand_state.get("finger_states", {}),
            metrics_per_finger=r.metrics_per_finger,
            tam_buffers_per_finger=r.tam_buffers_snapshot,
        )

    def _on_camera_error(self, message: str) -> None:
        """
        Handles fatal camera errors emitted by CameraWorker.

        When the camera stops working during an active session,
        automatically ends the session to prevent recording
        invalid frames to the CSV. Displays the error in log and status bar.

        Parameters:
            message: Error description sent by CameraWorker via signal.
        """
        self.log_widget.log_error(f"Camera: {message}")
        self.video_widget.set_no_signal(message)
        self._status_bar.showMessage(f"CAMERA ERROR: {message}")
        logger.error("Camera error: %s", message)

        # If session was running, automatically terminate.
        # Continuing to record without frames creates a corrupted CSV.
        if self._state == "RUNNING":
            self._end_session()

    def _on_patient_name_changed(self, text: str) -> None:
        """
        Reacts to patient name changes in the form.

        Called by the name QLineEdit's textChanged signal on every keystroke.
        Checks if the form is ready (is_ready()) and transitions between
        IDLE and READY states accordingly.

        Parameters:
            text: Current text in the name field (raw string, including spaces).
        """
        # Only alters state if not in RUNNING or STOPPED.
        # We don't want name typing to change state during a session.
        if self._state in ("IDLE", "READY"):
            if self.session_header.is_ready():
                self._set_state("READY")
            else:
                self._set_state("IDLE")

    # =========================================================================
    # BUTTON ACTIONS
    # =========================================================================

    def _new_session(self) -> None:
        """
        Completely resets the system state and prepares UI for a new patient.

        Why recreate workers instead of just resetting?
            QThread in Qt has a unidirectional lifecycle: once run()
            returns and the thread ends, the QThread object cannot be restarted
            with start() again. Furthermore, _cleanup() in ProcessingWorker
            closes MediaPipe (self._hands.close()), and _release_camera() in
            CameraWorker releases cv2.VideoCapture. These resources need to be
            recreated from scratch for a new session to work.

            The safe solution is: destroy old workers, create new ones, and
            reconnect all signals.
        """
        if self._state == "RUNNING":
            QMessageBox.warning(self, "Warning", "Please end the current session before starting a new one.")
            return

        # User confirmation to prevent accidental data loss on screen
        resp = QMessageBox.question(
            self,
            "Attention: New Session",
            "Starting a new session will clear all current charts and metrics from the screen.\n\n"
            "Make sure you have exported the CSV or generated the PDF Report if you need this data.\n\n"
            "Are you sure you want to start from scratch?",
            QMessageBox.StandardButton.Yes | QMessageBox.StandardButton.No,
            QMessageBox.StandardButton.No  # Default to No for safety
        )
        if resp != QMessageBox.StandardButton.Yes:
            return

        # === 1. Ensure old workers are completely stopped ===
        if self.camera_worker.isRunning():
            self.camera_worker.stop()
            self.camera_worker.wait(3000)

        if self.processing_worker.isRunning():
            self.processing_worker.stop()
            self.processing_worker.wait(3000)

        # === 2. Recreate workers from scratch (new QThread objects) ===
        self._create_workers()

        # === 3. Reconnect all signals to new workers ===
        self._connect_signals()

        # === 4. Clear all UI widgets ===
        self.video_widget.set_no_signal("Waiting for new session...")
        self.plot_widget.clear_data()
        self.finger_cards.clear_all()
        self.metrics_widget.reset_display()
        self.metrics_widget.stop_monitoring()
        self.session_header.reset()

        # === 5. Clear the log and display confirmation ===
        self.log_widget.clear_log()
        self.log_widget.log_success("System restarted. Ready for a new session.")

        # === 6. Reset session references ===
        self._csv_path = ""
        self._pdf_worker = None

        # === 7. Re-evaluate state ===
        if self.session_header.is_ready():
            self._set_state("READY")
        else:
            self._set_state("IDLE")

    def _start_session(self) -> None:
        """
        Starts the goniometric capture and processing session.

        Operation sequence:
            1. Validates if form is complete (is_ready()).
            2. Creates the logs directory if it doesn't exist.
            3. Generates the CSV path with a timestamp for uniqueness.
            4. Starts the session in ProcessingWorker (opens CSV).
            5. Starts the worker threads.
            6. Updates the timer and log.
            7. Transitions to the RUNNING state.

        Called by the "Start Session" button (btn_start).
        """
        # Precondition validation — extra defense line beyond the READY state.
        if not self.session_header.is_ready():
            QMessageBox.warning(
                self,
                "Incomplete Data",
                "Please fill in the full patient name before starting.",
            )
            return

        # Collect form data for use in CSV and PDF.
        session_info = self.session_header.get_session_info()
        patient_name: str = session_info["patient_name"]
        hand: str = session_info["hand"]
        session_number: int = session_info["session_number"]

        # Create the logs folder if it does not exist.
        # exist_ok=True: no error if folder already exists.
        os.makedirs(config.LOG_DIR, exist_ok=True)

        # Generate the CSV filename with a timestamp to ensure uniqueness.
        # Format: "logs/session_John_Doe_20260623_143512_s1.csv"
        # The timestamp prevents overwriting prior sessions of the same patient.
        timestamp_str: str = datetime.now().strftime("%Y%m%d_%H%M%S")
        # Remove invalid filename characters (spaces → underscores).
        safe_name: str = patient_name.replace(" ", "_").replace("/", "_")
        csv_filename: str = f"session_{safe_name}_{timestamp_str}_s{session_number}.csv"
        self._csv_path = os.path.join(config.LOG_DIR, csv_filename)

        # Start the CSV session in the worker BEFORE starting threads.
        # This ensures the logger is ready when the first frames arrive.
        self.processing_worker.start_session(self._csv_path)

        # Clear widget data from previous session.
        self.plot_widget.clear_data()
        self.finger_cards.clear_all()
        self.metrics_widget.reset_display()

        # Start worker threads.
        # start() from QThread calls run() in a separate thread.
        # Workers already exist since __init__ — we just start execution.
        if not self.camera_worker.isRunning():
            self.camera_worker.start()

        if not self.processing_worker.isRunning():
            self.processing_worker.start()

        # Start the timer in the header.
        self.session_header.start_timer()

        # Log startup and transition to RUNNING.
        self.log_widget.log_success(
            f"Session {session_number} started — {patient_name} | Hand {hand} | {csv_filename}"
        )

        self._set_state("RUNNING")
        logger.info(
            "Session started: patient=%s, hand=%s, session=%d, csv=%s",
            patient_name, hand, session_number, self._csv_path,
        )

    def _end_session(self) -> None:
        """
        Ends the capture session and finalizes the CSV file.

        Operation sequence:
            1. Signals ProcessingWorker to close the CSV session.
            2. Signals CameraWorker to stop the capture loop.
            3. Stops the timer.
            4. Logs the event.
            5. Transitions to the STOPPED state.

        Called by the "End Session" button (btn_end) OR automatically
        by _on_camera_error() when the camera fails during an active session.

        Note: wait() is not used here to avoid blocking the main thread.
        closeEvent() uses wait() with a timeout when the window is closed.
        """
        # Close the CSV recording safely (flush + close).
        self.processing_worker.stop_session()

        # Signal CameraWorker to stop the capture loop.
        # The loop in run() will check the event on its next iteration.
        self.camera_worker.stop()

        # Stop the timer — the display freezes at the total session time.
        self.session_header.stop_timer()

        self.log_widget.log_success(
            f"Session ended. CSV saved to: {self._csv_path}"
        )
        self._set_state("STOPPED")
        logger.info("Session ended. CSV: %s", self._csv_path)

    def _gerar_relatorio(self) -> None:
        """
        Generates the PDF report of the ended session in a separate thread.

        Why a separate thread? (See _PdfGeneratorWorker for full explanation)
        In short: generate_pdf_report() can take 5–15 seconds (Matplotlib +
        FPDF) and would completely freeze the interface if run on the main thread.

        Behavior:
            - Disables the PDF button during generation (prevents double-clicks).
            - Displays a status bar message indicating progress.
            - On finish, _on_pdf_finished() shows a success dialog.
            - On failure, _on_pdf_error() shows an error dialog.

        Called by the "Generate PDF Report" button (btn_pdf).
        """
        if not self._csv_path or not os.path.exists(self._csv_path):
            QMessageBox.warning(
                self,
                "CSV Not Found",
                f"The session's CSV file was not found:\n{self._csv_path}\n\n"
                "Verify if the session was properly ended.",
            )
            return

        session_info = self.session_header.get_session_info()

        # Disable the button during generation to prevent double clicks.
        self.btn_pdf.setEnabled(False)
        self.btn_pdf.setText("⏳  Generating PDF...")
        self._status_bar.showMessage("Generating PDF report... Please wait.")
        self.log_widget.log("Starting PDF report generation...")

        # Create and configure the PDF generation worker.
        self._pdf_worker = _PdfGeneratorWorker(
            csv_path=self._csv_path,
            patient_name=session_info["patient_name"],
            side=session_info["hand"],
            logo_path=os.path.abspath(os.path.join("assets", "logo_clinic.png")),
            parent=self,
        )

        # Connect completion and error signals to the worker.
        self._pdf_worker.finished_signal.connect(self._on_pdf_finished)
        self._pdf_worker.error_signal.connect(self._on_pdf_error)

        # Start the PDF worker on the separate thread.
        self._pdf_worker.start()

    def _on_pdf_finished(self, pdf_path: str) -> None:
        """
        Handles the successful completion of the PDF generation.

        Called by the finished_signal from _PdfGeneratorWorker when
        the PDF was successfully generated. Restores the button and displays the result.

        Parameters:
            pdf_path: Absolute path to the generated PDF file.
        """
        # Restore button to original state.
        self.btn_pdf.setEnabled(True)
        self.btn_pdf.setText("📄  Generate PDF Report")
        self._status_bar.showMessage(f"PDF generated: {pdf_path}")
        self.log_widget.log_success(f"PDF Report generated: {pdf_path}")

        # Display dialog with the PDF path.
        msg = QMessageBox(self)
        msg.setWindowTitle("Report Generated")
        msg.setIcon(QMessageBox.Icon.Information)
        msg.setText("✅ PDF Report successfully generated!")
        msg.setInformativeText(f"File saved to:\n{pdf_path}")
        msg.exec()

    def _on_pdf_error(self, error_message: str) -> None:
        """
        Handles a PDF generation failure.

        Called by the error_signal from _PdfGeneratorWorker when
        generation fails (invalid CSV, disk full, missing Matplotlib etc.).

        Parameters:
            error_message: Error description returned by the exception.
        """
        # Restore button and report the error.
        self.btn_pdf.setEnabled(True)
        self.btn_pdf.setText("📄  Generate PDF Report")
        self._status_bar.showMessage("Failed to generate PDF report.")
        self.log_widget.log_error(f"Failed to generate PDF: {error_message}")

        QMessageBox.critical(
            self,
            "PDF Generation Error",
            f"Could not generate the PDF report.\n\nDetail:\n{error_message}",
        )

    def _exportar_csv(self) -> None:
        """
        Exports the session CSV to a user-selected location.

        Opens a file dialog for the user to choose where to save
        a copy of the CSV. Uses shutil.copy() to preserve original data.
        The original file in config.LOG_DIR is not moved or deleted.

        Called by the "Export CSV" button (btn_csv).
        """
        if not self._csv_path or not os.path.exists(self._csv_path):
            QMessageBox.warning(
                self,
                "CSV Not Found",
                "There is no CSV file available for export.",
            )
            return

        # QFileDialog.getSaveFileName: native "Save As" dialog.
        # Suggests the original filename by default.
        default_name = os.path.basename(self._csv_path)
        destination, selected_filter = QFileDialog.getSaveFileName(
            parent=self,
            caption="Export Session CSV",
            directory=default_name,
            filter="CSV Files (*.csv);;All Files (*)",
        )

        # If the user canceled the dialog, destination is an empty string.
        if not destination:
            return

        try:
            # Copy the original CSV file to the chosen destination.
            # shutil.copy() copies content AND permissions, more robust than open().
            shutil.copy(self._csv_path, destination)
            self.log_widget.log_success(f"CSV exported to: {destination}")
            self._status_bar.showMessage(f"CSV exported: {destination}")

            QMessageBox.information(
                self,
                "Export Complete",
                f"✅ CSV successfully exported to:\n{destination}",
            )

        except (OSError, shutil.Error) as exc:
            self.log_widget.log_error(f"Failed to export CSV: {exc}")
            QMessageBox.critical(
                self,
                "Export Error",
                f"Could not export the CSV.\n\nDetail:\n{exc}",
            )

    def _abrir_historico(self) -> None:
        """
        Opens the folder where session files are saved in the file explorer.

        Uses os.startfile() on Windows to open the folder in File Explorer.
        The folder is created if it does not exist before trying to open.

        Called by the "Open Sessions Folder" button (btn_historico).
        """
        # Ensure the folder exists before trying to open.
        os.makedirs(config.LOG_DIR, exist_ok=True)
        abs_log_dir: str = os.path.abspath(config.LOG_DIR)

        try:
            # os.startfile() is Windows-exclusive — opens with default program.
            # On Windows, opens File Explorer at the specified folder.
            os.startfile(abs_log_dir)
        except AttributeError:
            # Fallback for Linux/macOS where os.startfile() does not exist.
            import subprocess
            subprocess.Popen(["xdg-open", abs_log_dir])
        except Exception as exc:
            self.log_widget.log_error(f"Could not open the folder: {exc}")

    # =========================================================================
    # WINDOW LIFECYCLE
    # =========================================================================

    def closeEvent(self, event) -> None:
        """
        Intercepts the window close event to terminate the workers.

        Called by Qt when the user clicks the window's "X" button or
        when QApplication.quit() is called.

        Why wait() with a timeout here and not in _end_session()?
            _end_session() is called during the session while the window
            is still visible — blocking the main thread with wait() there
            would freeze the interface for a few frames. Here, the window is
            closing anyway, so the temporary block is acceptable to ensure
            that workers terminate cleanly.

        Sequence:
            1. Stops the workers (signals termination).
            2. Waits up to 3000ms per worker to finish.
            3. Accepts the close event (window closes).

        Parameters:
            event: QCloseEvent provided by Qt with the close event.
        """
        logger.info("closeEvent: stopping workers before closing.")

        # End active session if there is one.
        if self._state == "RUNNING":
            self.processing_worker.stop_session()

        # Stop and wait for CameraWorker.
        if self.camera_worker.isRunning():
            self.camera_worker.stop()
            # wait(3000): waits up to 3 seconds. If worker does not finish,
            # Qt will force-terminate the thread upon app close.
            self.camera_worker.wait(3000)

        # Stop and wait for ProcessingWorker.
        if self.processing_worker.isRunning():
            self.processing_worker.stop()
            self.processing_worker.wait(3000)

        # Stop the PDF worker if generating.
        if self._pdf_worker is not None and self._pdf_worker.isRunning():
            self._pdf_worker.wait(5000)

        logger.info("closeEvent: workers stopped. Closing window.")

        # Accept the event — the window closes normally.
        event.accept()
